//! Generators for the Markdown command reference, the man page, and shell
//! completions.
//!
//! All three read the same `CommandSpec` tree that the parser walks and
//! `--help` prints, so a new command or option appears in the docs, the man
//! page, and every shell's completion without a second place to update.
//!
//! `zig build docs` writes the generated files into the repo; `zig build
//! docs-check` regenerates them into a temporary directory and fails if the
//! committed copies have drifted.

const std = @import("std");
const spec = @import("spec.zig");

pub const Shell = enum {
    bash,
    zsh,
    fish,

    pub fn parse(text: []const u8) ?Shell {
        return std.meta.stringToEnum(Shell, text);
    }
};

/// One command in the tree, paired with its full path (`"scene node add"`).
/// The root itself is not an entry; only its descendants are.
const Entry = struct {
    path: []const u8,
    command: *const spec.CommandSpec,
    depth: usize,
};

fn collect(
    allocator: std.mem.Allocator,
    parent: *const spec.CommandSpec,
    prefix: []const u8,
    depth: usize,
    out: *std.ArrayList(Entry),
) !void {
    for (parent.children, 0..) |_, index| {
        const child = &parent.children[index];
        const path = if (prefix.len == 0)
            try allocator.dupe(u8, child.name)
        else
            try std.fmt.allocPrint(allocator, "{s} {s}", .{ prefix, child.name });

        try out.append(allocator, .{ .path = path, .command = child, .depth = depth });
        try collect(allocator, child, path, depth + 1, out);
    }
}

fn entries(allocator: std.mem.Allocator, root: *const spec.CommandSpec) ![]Entry {
    var list: std.ArrayList(Entry) = .empty;
    try collect(allocator, root, "", 0, &list);
    return list.items;
}

fn valuePlaceholder(kind: spec.ValueKind) []const u8 {
    return switch (kind) {
        .flag => "",
        .string => "<value>",
        .path => "<path>",
    };
}

// ---------------------------------------------------------------------------
// Markdown command reference
// ---------------------------------------------------------------------------

pub fn markdown(
    allocator: std.mem.Allocator,
    root: *const spec.CommandSpec,
    tool_name: []const u8,
    summary: []const u8,
) ![]u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    const all = try entries(arena, root);

    try w.print(
        \\# Command reference
        \\
        \\<!-- Generated by `zig build docs` from the command tree in src/commands.zig.
        \\     Edit the CommandSpec entries there, not this file. -->
        \\
        \\`{s}` — {s}
        \\
        \\Every command accepts the [global options](#global-options), and with `--json`
        \\returns the envelope described in
        \\[development principles](development_principles.md#json-output---json).
        \\
        \\```
        \\{s} [global options] <command> [command options] [args...]
        \\```
        \\
        \\## Global options
        \\
        \\| Option | Value | Description |
        \\|--------|-------|-------------|
        \\
    , .{ tool_name, summary, tool_name });

    for (spec.global_options) |opt| {
        try w.writeAll("| ");
        if (opt.short) |short_char| {
            try w.print("`-{c}`, `--{s}`", .{ short_char, opt.long });
        } else {
            try w.print("`--{s}`", .{opt.long});
        }
        try w.writeAll(" | ");
        const placeholder = valuePlaceholder(opt.kind);
        if (placeholder.len == 0) try w.writeAll("—") else try w.print("`{s}`", .{placeholder});
        try w.writeAll(" | ");
        try writeMarkdownCell(w, opt.description);
        try w.writeAll(" |\n");
    }

    try w.writeAll(
        \\
        \\## Command index
        \\
        \\| Command | Summary |
        \\|---------|---------|
        \\
    );

    for (all) |entry| {
        try w.print("| [`{s} {s}`](#", .{ tool_name, entry.path });
        try writeAnchor(w, tool_name);
        try w.writeAll("-");
        try writeAnchor(w, entry.path);
        try w.writeAll(") | ");
        try writeMarkdownCell(w, entry.command.summary);
        try w.writeAll(" |\n");
    }

    try w.writeAll("\n## Commands\n");

    for (all) |entry| {
        try w.print("\n### `{s} {s}`\n\n", .{ tool_name, entry.path });
        try writeMarkdownText(w, entry.command.summary);
        try w.writeAll("\n");

        if (entry.command.description) |description| {
            try w.writeAll("\n");
            try writeMarkdownText(w, description);
            try w.writeAll("\n");
        }

        try w.print("\n```\n{s} {s}", .{ tool_name, entry.path });
        if (entry.command.options.len != 0 or entry.command.children.len != 0) {
            try w.writeAll(" [options]");
        }
        for (entry.command.positionals) |arg| {
            try w.writeAll(" ");
            try writePositionalUsage(w, arg);
        }
        try w.writeAll("\n```\n");

        if (entry.command.children.len != 0) {
            try w.writeAll("\n**Subcommands**\n\n| Subcommand | Summary |\n|------------|---------|\n");
            for (entry.command.children) |child| {
                try w.print("| [`{s}`](#", .{child.name});
                try writeAnchor(w, tool_name);
                try w.writeAll("-");
                try writeAnchor(w, entry.path);
                try w.writeAll("-");
                try writeAnchor(w, child.name);
                try w.writeAll(") | ");
                try writeMarkdownCell(w, child.summary);
                try w.writeAll(" |\n");
            }
        }

        if (entry.command.positionals.len != 0) {
            try w.writeAll("\n**Arguments**\n\n| Argument | Description |\n|----------|-------------|\n");
            for (entry.command.positionals) |arg| {
                try w.writeAll("| `");
                try writePositionalUsage(w, arg);
                try w.writeAll("` | ");
                try writeMarkdownCell(w, arg.description);
                if (!arg.required) try w.writeAll(" (optional)");
                try w.writeAll(" |\n");
            }
        }

        if (entry.command.options.len != 0) {
            try w.writeAll("\n**Options**\n\n| Option | Value | Description | Default |\n|--------|-------|-------------|---------|\n");
            for (entry.command.options) |opt| {
                try w.writeAll("| ");
                if (opt.short) |short_char| {
                    try w.print("`-{c}`, `--{s}`", .{ short_char, opt.long });
                } else {
                    try w.print("`--{s}`", .{opt.long});
                }
                try w.writeAll(" | ");
                const placeholder = valuePlaceholder(opt.kind);
                if (placeholder.len == 0) try w.writeAll("—") else try w.print("`{s}`", .{placeholder});
                try w.writeAll(" | ");
                try writeMarkdownCell(w, opt.description);
                try w.writeAll(" | ");
                if (opt.default_value) |default_value| {
                    try w.print("`{s}`", .{default_value});
                } else {
                    try w.writeAll("—");
                }
                try w.writeAll(" |\n");
            }
        }
    }

    try w.writeAll(
        \\
        \\## Exit codes
        \\
        \\| Code | Meaning |
        \\|------|---------|
        \\| `0` | Success |
        \\| `1` | Runtime or command failure |
        \\| `2` | Usage or invocation error |
        \\
    );

    return allocator.dupe(u8, out.written());
}

/// Pipes end a table cell and newlines end a row, so both have to go. Angle
/// brackets are escaped because option descriptions use them as placeholders
/// (`<scene>.manifest.json`), and a Markdown renderer reads those as HTML tags.
fn writePositionalUsage(w: *std.Io.Writer, arg: spec.PositionalSpec) !void {
    try w.print("{c}{s}{c}{s}", .{
        @as(u8, if (arg.required) '<' else '['),
        arg.name,
        @as(u8, if (arg.required) '>' else ']'),
        if (arg.variadic) "..." else "",
    });
}

fn writeMarkdownCell(w: *std.Io.Writer, text: []const u8) !void {
    for (text) |byte| switch (byte) {
        '|' => try w.writeAll("\\|"),
        '\n' => try w.writeAll(" "),
        '<' => try w.writeAll("&lt;"),
        '>' => try w.writeAll("&gt;"),
        else => try w.writeByte(byte),
    };
}

/// Prose outside a table: keeps newlines, still escapes angle brackets.
fn writeMarkdownText(w: *std.Io.Writer, text: []const u8) !void {
    for (text) |byte| switch (byte) {
        '<' => try w.writeAll("&lt;"),
        '>' => try w.writeAll("&gt;"),
        else => try w.writeByte(byte),
    };
}

/// GitHub heading anchors: lowercase, spaces to hyphens, punctuation dropped.
fn writeAnchor(w: *std.Io.Writer, text: []const u8) !void {
    for (text) |byte| {
        if (byte == ' ') {
            try w.writeByte('-');
        } else if (std.ascii.isAlphanumeric(byte) or byte == '-' or byte == '_') {
            try w.writeByte(std.ascii.toLower(byte));
        }
    }
}

// ---------------------------------------------------------------------------
// Machine-readable command tree
// ---------------------------------------------------------------------------

/// The whole command surface as JSON: one object per command, in the order the
/// tree declares them. Consumers that wrap the CLI — an MCP server, a tool
/// catalog, a docs site — can read this instead of scraping `--help`.
pub fn commandTree(
    allocator: std.mem.Allocator,
    root: *const spec.CommandSpec,
    tool_name: []const u8,
    version_string: []const u8,
) !std.json.Value {
    var commands_json: std.json.Array = .init(allocator);

    const all = try entries(allocator, root);
    for (all) |entry| {
        var row: std.json.ObjectMap = .{};
        try row.put(allocator, "path", .{ .string = entry.path });
        try row.put(allocator, "name", .{ .string = entry.command.name });
        try row.put(allocator, "summary", .{ .string = entry.command.summary });
        if (entry.command.description) |description| {
            try row.put(allocator, "description", .{ .string = description });
        }
        try row.put(allocator, "runnable", .{ .bool = entry.command.handler != null });

        var positionals_json: std.json.Array = .init(allocator);
        for (entry.command.positionals) |arg| {
            var arg_row: std.json.ObjectMap = .{};
            try arg_row.put(allocator, "name", .{ .string = arg.name });
            try arg_row.put(allocator, "kind", .{ .string = @tagName(arg.kind) });
            try arg_row.put(allocator, "description", .{ .string = arg.description });
            try arg_row.put(allocator, "required", .{ .bool = arg.required });
            try arg_row.put(allocator, "variadic", .{ .bool = arg.variadic });
            try positionals_json.append(.{ .object = arg_row });
        }
        try row.put(allocator, "positionals", .{ .array = positionals_json });

        var options_json: std.json.Array = .init(allocator);
        for (entry.command.options) |opt| {
            var option_row: std.json.ObjectMap = .{};
            try option_row.put(allocator, "long", .{ .string = opt.long });
            if (opt.short) |short_char| {
                try option_row.put(allocator, "short", .{ .string = try allocator.dupe(u8, &.{short_char}) });
            }
            try option_row.put(allocator, "kind", .{ .string = @tagName(opt.kind) });
            try option_row.put(allocator, "description", .{ .string = opt.description });
            if (opt.default_value) |default_value| {
                try option_row.put(allocator, "default", .{ .string = default_value });
            }
            if (opt.repeatable) try option_row.put(allocator, "repeatable", .{ .bool = true });
            try options_json.append(.{ .object = option_row });
        }
        try row.put(allocator, "options", .{ .array = options_json });

        var children_json: std.json.Array = .init(allocator);
        for (entry.command.children) |child| {
            try children_json.append(.{ .string = child.name });
        }
        try row.put(allocator, "subcommands", .{ .array = children_json });

        try commands_json.append(.{ .object = row });
    }

    var globals_json: std.json.Array = .init(allocator);
    for (spec.global_options) |opt| {
        var option_row: std.json.ObjectMap = .{};
        try option_row.put(allocator, "long", .{ .string = opt.long });
        if (opt.short) |short_char| {
            try option_row.put(allocator, "short", .{ .string = try allocator.dupe(u8, &.{short_char}) });
        }
        try option_row.put(allocator, "kind", .{ .string = @tagName(opt.kind) });
        try option_row.put(allocator, "description", .{ .string = opt.description });
        try globals_json.append(.{ .object = option_row });
    }

    var tree: std.json.ObjectMap = .{};
    try tree.put(allocator, "name", .{ .string = tool_name });
    try tree.put(allocator, "version", .{ .string = version_string });
    try tree.put(allocator, "global_options", .{ .array = globals_json });
    try tree.put(allocator, "commands", .{ .array = commands_json });
    return .{ .object = tree };
}

// ---------------------------------------------------------------------------
// Man page
// ---------------------------------------------------------------------------

pub fn manPage(
    allocator: std.mem.Allocator,
    root: *const spec.CommandSpec,
    tool_name: []const u8,
    summary: []const u8,
    version_string: []const u8,
    version_date: []const u8,
) ![]u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    const all = try entries(arena, root);

    // The date comes from the build (the release date of `version_string`),
    // never from the clock: a timestamp would make two identical trees
    // generate different files and break `zig build docs-check`.
    try w.print(
        ".TH GODOT\\-CLI 1 \"{s}\" \"{s} {s}\" \"{s} Manual\"\n",
        .{ version_date, tool_name, version_string, tool_name },
    );

    try w.writeAll(".SH NAME\n");
    try writeRoff(w, tool_name);
    try w.writeAll(" \\- ");
    try writeRoff(w, summary);
    try w.writeAll("\n");

    try w.writeAll(".SH SYNOPSIS\n.B ");
    try writeRoff(w, tool_name);
    try w.writeAll("\n");
    try w.writeAll("[\\fIglobal options\\fR] \\fIcommand\\fR [\\fIcommand options\\fR] [\\fIargs\\fR...]\n.br\n");
    try w.writeAll(".B ");
    try writeRoff(w, tool_name);
    try w.writeAll("\n\\fB\\-\\-request\\fR \\fIjson\\fR\n.br\n.B ");
    try writeRoff(w, tool_name);
    try w.writeAll("\n\\fB\\-\\-request\\-file\\fR \\fIpath\\fR\n.br\n.B ");
    try writeRoff(w, tool_name);
    try w.writeAll("\n\\fB\\-\\-request\\-stdin\\fR\n");

    try w.writeAll(".SH DESCRIPTION\n");
    try w.writeAll(
        \\Reads and writes Godot 4 scene
        \\.RB ( .tscn ),
        \\resource
        \\.RB ( .tres ),
        \\and
        \\.B project.godot
        \\files with the same identifiers, ordering, and Variant formatting the Godot
        \\editor writes, so files it produces are byte-comparable with editor saves.
        \\.PP
        \\Commands form a tree. Anything expressible on the command line is also
        \\expressible as a JSON request document, and with
        \\.B \-\-json
        \\every command returns one JSON envelope on standard output.
        \\
    );

    try w.writeAll(".SH GLOBAL OPTIONS\n");
    for (spec.global_options) |opt| {
        try w.writeAll(".TP\n");
        if (opt.short) |short_char| {
            try w.print("\\fB\\-{c}\\fR, \\fB\\-\\-", .{short_char});
        } else {
            try w.writeAll("\\fB\\-\\-");
        }
        try writeRoff(w, opt.long);
        try w.writeAll("\\fR");
        const placeholder = valuePlaceholder(opt.kind);
        if (placeholder.len != 0) {
            try w.print(" \\fI{s}\\fR", .{std.mem.trim(u8, placeholder, "<>")});
        }
        try w.writeAll("\n");
        try writeRoff(w, opt.description);
        try w.writeAll("\n");
    }

    try w.writeAll(".SH COMMANDS\n");
    for (all) |entry| {
        try w.writeAll(".SS ");
        try writeRoff(w, tool_name);
        try w.writeAll(" ");
        try writeRoff(w, entry.path);
        try w.writeAll("\n");
        try writeRoff(w, entry.command.summary);
        try w.writeAll("\n");

        if (entry.command.description) |description| {
            try w.writeAll(".PP\n");
            try writeRoff(w, description);
            try w.writeAll("\n");
        }

        for (entry.command.positionals) |arg| {
            try w.writeAll(".TP\n\\fI");
            try writeRoff(w, arg.name);
            if (arg.variadic) try w.writeAll("...");
            try w.writeAll("\\fR\n");
            try writeRoff(w, arg.description);
            if (!arg.required) try w.writeAll(" (optional)");
            try w.writeAll("\n");
        }

        for (entry.command.options) |opt| {
            try w.writeAll(".TP\n");
            if (opt.short) |short_char| {
                try w.print("\\fB\\-{c}\\fR, \\fB\\-\\-", .{short_char});
            } else {
                try w.writeAll("\\fB\\-\\-");
            }
            try writeRoff(w, opt.long);
            try w.writeAll("\\fR");
            const placeholder = valuePlaceholder(opt.kind);
            if (placeholder.len != 0) {
                try w.print(" \\fI{s}\\fR", .{std.mem.trim(u8, placeholder, "<>")});
            }
            try w.writeAll("\n");
            try writeRoff(w, opt.description);
            if (opt.default_value) |default_value| {
                try w.writeAll(" (default: ");
                try writeRoff(w, default_value);
                try w.writeAll(")");
            }
            try w.writeAll("\n");
        }
    }

    try w.writeAll(
        \\.SH EXIT STATUS
        \\.TP
        \\.B 0
        \\Success.
        \\.TP
        \\.B 1
        \\Runtime or command failure.
        \\.TP
        \\.B 2
        \\Usage or invocation error.
        \\.SH ENVIRONMENT
        \\.TP
        \\.B GODOT_CLI_TEMPLATES_ROOT
        \\Directory searched for built\-in scene templates when
        \\.B \-\-templates\-root
        \\is not given.
        \\.SH SEE ALSO
        \\Project documentation, including the agent guides and the full command
        \\reference, ships in the release archive and lives at
        \\.UR https://github.com/unabated\\-games/godot\\-cli
        \\github.com/unabated\\-games/godot\\-cli
        \\.UE
        \\
    );

    return allocator.dupe(u8, out.written());
}

/// Escape roff control characters and wrap long input lines.
///
/// A leading dot or apostrophe starts a roff request and a backslash starts an
/// escape, so all three are quoted. Wrapping is cosmetic — roff refills the
/// text anyway — but it keeps the generated source lint-clean and reviewable in
/// a diff.
fn writeRoff(w: *std.Io.Writer, text: []const u8) !void {
    // Short enough that even a long trailing token lands inside the 80-byte
    // line mandoc lints for.
    const wrap_column = 58;
    var at_line_start = true;
    var column: usize = 0;

    var index: usize = 0;
    while (index < text.len) : (index += 1) {
        const byte = text[index];

        if (byte == ' ' and column >= wrap_column and index + 1 < text.len and text[index + 1] != ' ') {
            try w.writeAll("\n");
            at_line_start = true;
            column = 0;
            continue;
        }

        // Count emitted bytes, not source bytes: an escaped hyphen is two
        // columns of generated line, and mandoc lints on the generated width.
        var emitted: usize = 1;
        switch (byte) {
            '\\' => {
                try w.writeAll("\\e");
                emitted = 2;
            },
            '-' => {
                try w.writeAll("\\-");
                emitted = 2;
            },
            '.', '\'' => {
                if (at_line_start) {
                    try w.writeAll("\\&");
                    emitted = 3;
                }
                try w.writeByte(byte);
            },
            '\n' => {
                try w.writeAll("\n");
                at_line_start = true;
                column = 0;
                continue;
            },
            else => try w.writeByte(byte),
        }

        at_line_start = false;
        column += emitted;
    }
}

// ---------------------------------------------------------------------------
// Shell completions
// ---------------------------------------------------------------------------

pub fn completions(
    allocator: std.mem.Allocator,
    root: *const spec.CommandSpec,
    tool_name: []const u8,
    shell: Shell,
) ![]u8 {
    var arena_state = std.heap.ArenaAllocator.init(allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;

    const all = try entries(arena, root);

    switch (shell) {
        .bash => try bashCompletions(w, root, all, tool_name),
        .zsh => try zshCompletions(w, root, all, tool_name),
        .fish => try fishCompletions(w, root, all, tool_name),
    }

    return allocator.dupe(u8, out.written());
}

fn bashCompletions(
    w: *std.Io.Writer,
    root: *const spec.CommandSpec,
    all: []const Entry,
    tool_name: []const u8,
) !void {
    try w.print(
        \\# bash completion for {s} — generated by `{s} completions bash`.
        \\#
        \\# Install: source this file from ~/.bashrc, or copy it into
        \\# /usr/local/etc/bash_completion.d/ (Homebrew) or /etc/bash_completion.d/.
        \\
        \\_godot_cli_children() {{
        \\    case "$1" in
        \\
    , .{ tool_name, tool_name });

    try writeBashChildrenCases(w, root, all);

    try w.writeAll(
        \\        *)
        \\            echo ""
        \\            ;;
        \\    esac
        \\}
        \\
        \\_godot_cli_options() {
        \\    case "$1" in
        \\
    );

    for (all) |entry| {
        if (entry.command.options.len == 0) continue;
        try w.print("        '{s}')\n            echo \"", .{entry.path});
        for (entry.command.options, 0..) |opt, index| {
            if (index != 0) try w.writeAll(" ");
            try w.print("--{s}", .{opt.long});
        }
        try w.writeAll("\"\n            ;;\n");
    }

    try w.writeAll(
        \\        *)
        \\            echo ""
        \\            ;;
        \\    esac
        \\}
        \\
        \\_godot_cli_takes_args() {
        \\    case "$1" in
        \\
    );

    for (all) |entry| {
        if (entry.command.handler == null) continue;
        try w.print("        '{s}') return 0 ;;\n", .{entry.path});
    }

    try w.writeAll(
        \\        *) return 1 ;;
        \\    esac
        \\}
        \\
        \\_godot_cli_global_options="
    );
    for (spec.global_options, 0..) |opt, index| {
        if (index != 0) try w.writeAll(" ");
        try w.print("--{s}", .{opt.long});
    }
    try w.writeAll("\"\n");

    // Word splitting on compgen output rather than `mapfile`: macOS still ships
    // bash 3.2, where mapfile does not exist.
    try w.print(
        \\
        \\_godot_cli() {{
        \\    local cur path="" word children candidates
        \\    COMPREPLY=()
        \\    cur="${{COMP_WORDS[COMP_CWORD]}}"
        \\
        \\    local index
        \\    for (( index = 1; index < COMP_CWORD; index++ )); do
        \\        word="${{COMP_WORDS[index]}}"
        \\        case "$word" in
        \\            -*) continue ;;
        \\        esac
        \\        children=" $(_godot_cli_children "$path") "
        \\        if [[ "$children" == *" $word "* ]]; then
        \\            path="${{path:+$path }}$word"
        \\        fi
        \\    done
        \\
        \\    candidates="$(_godot_cli_children "$path") $(_godot_cli_options "$path") $_godot_cli_global_options"
        \\    COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )
        \\
        \\    # Leaf commands nearly all take a path; offer files once the word
        \\    # being completed is clearly not a flag.
        \\    if [[ "$cur" != -* ]] && _godot_cli_takes_args "$path"; then
        \\        COMPREPLY+=( $(compgen -f -- "$cur") )
        \\    fi
        \\}}
        \\
        \\complete -F _godot_cli {s}
        \\
    , .{tool_name});
}

fn writeBashChildrenCases(
    w: *std.Io.Writer,
    root: *const spec.CommandSpec,
    all: []const Entry,
) !void {
    try w.writeAll("        '')\n            echo \"");
    for (root.children, 0..) |child, index| {
        if (index != 0) try w.writeAll(" ");
        try w.writeAll(child.name);
    }
    try w.writeAll("\"\n            ;;\n");

    for (all) |entry| {
        if (entry.command.children.len == 0) continue;
        try w.print("        '{s}')\n            echo \"", .{entry.path});
        for (entry.command.children, 0..) |child, index| {
            if (index != 0) try w.writeAll(" ");
            try w.writeAll(child.name);
        }
        try w.writeAll("\"\n            ;;\n");
    }
}

fn zshCompletions(
    w: *std.Io.Writer,
    root: *const spec.CommandSpec,
    all: []const Entry,
    tool_name: []const u8,
) !void {
    try w.print(
        \\#compdef {s}
        \\# zsh completion for {s} — generated by `{s} completions zsh`.
        \\#
        \\# Install: save as _{s} in a directory on $fpath, then run `compinit`.
        \\
        \\_godot_cli_children() {{
        \\    case "$1" in
        \\
    , .{ tool_name, tool_name, tool_name, tool_name });

    try w.writeAll("        '')\n            _godot_cli_reply=(");
    for (root.children) |child| {
        try w.writeAll(" ");
        try writeZshPair(w, "", child.name, child.summary);
    }
    try w.writeAll(" )\n            ;;\n");

    for (all) |entry| {
        if (entry.command.children.len == 0) continue;
        try w.print("        '{s}')\n            _godot_cli_reply=(", .{entry.path});
        for (entry.command.children) |child| {
            try w.writeAll(" ");
            try writeZshPair(w, "", child.name, child.summary);
        }
        try w.writeAll(" )\n            ;;\n");
    }

    try w.writeAll(
        \\        *)
        \\            _godot_cli_reply=()
        \\            ;;
        \\    esac
        \\}
        \\
        \\_godot_cli_options() {
        \\    case "$1" in
        \\
    );

    for (all) |entry| {
        if (entry.command.options.len == 0) continue;
        try w.print("        '{s}')\n            _godot_cli_reply=(", .{entry.path});
        for (entry.command.options) |opt| {
            try w.writeAll(" ");
            try writeZshPair(w, "--", opt.long, opt.description);
        }
        try w.writeAll(" )\n            ;;\n");
    }

    try w.writeAll(
        \\        *)
        \\            _godot_cli_reply=()
        \\            ;;
        \\    esac
        \\}
        \\
        \\_godot_cli_global_options=(
    );
    for (spec.global_options) |opt| {
        try w.writeAll(" ");
        try writeZshPair(w, "--", opt.long, opt.description);
    }
    try w.writeAll(" )\n");

    try w.print(
        \\
        \\_{s}() {{
        \\    local -a _godot_cli_reply subcommands options names
        \\    local path="" word
        \\    integer index
        \\
        \\    for (( index = 2; index < CURRENT; index++ )); do
        \\        word="${{words[index]}}"
        \\        [[ "$word" == -* ]] && continue
        \\        _godot_cli_children "$path"
        \\        names=( ${{_godot_cli_reply%%:*}} )
        \\        if (( ${{names[(I)$word]}} )); then
        \\            path="${{path:+$path }}$word"
        \\        fi
        \\    done
        \\
        \\    _godot_cli_children "$path"
        \\    subcommands=( "${{_godot_cli_reply[@]}}" )
        \\    _godot_cli_options "$path"
        \\    options=( "${{_godot_cli_reply[@]}}" )
        \\
        \\    (( ${{#subcommands}} )) && _describe -t commands 'command' subcommands
        \\    (( ${{#options}} )) && _describe -t options 'option' options
        \\    _describe -t globals 'global option' _godot_cli_global_options
        \\    _files
        \\}}
        \\
        \\_{s} "$@"
        \\
    , .{ tool_name, tool_name });
}

fn fishCompletions(
    w: *std.Io.Writer,
    root: *const spec.CommandSpec,
    all: []const Entry,
    tool_name: []const u8,
) !void {
    try w.print(
        \\# fish completion for {s} — generated by `{s} completions fish`.
        \\#
        \\# Install: save as ~/.config/fish/completions/{s}.fish
        \\
        \\function __godot_cli_children
        \\    switch "$argv[1]"
        \\
    , .{ tool_name, tool_name, tool_name });

    try w.writeAll("        case ''\n            echo '");
    for (root.children, 0..) |child, index| {
        if (index != 0) try w.writeAll(" ");
        try w.writeAll(child.name);
    }
    try w.writeAll("'\n");

    for (all) |entry| {
        if (entry.command.children.len == 0) continue;
        try w.print("        case '{s}'\n            echo '", .{entry.path});
        for (entry.command.children, 0..) |child, index| {
            if (index != 0) try w.writeAll(" ");
            try w.writeAll(child.name);
        }
        try w.writeAll("'\n");
    }

    try w.print(
        \\        case '*'
        \\            echo ''
        \\    end
        \\end
        \\
        \\# Rebuild the command path from the words typed so far, ignoring flags
        \\# and any word that is not a child of the path resolved before it.
        \\function __godot_cli_path
        \\    set -l tokens (commandline -opc)
        \\    set -l path ''
        \\    for token in $tokens[2..-1]
        \\        if string match -q -- '-*' $token
        \\            continue
        \\        end
        \\        set -l children (string split ' ' -- (__godot_cli_children "$path"))
        \\        if contains -- $token $children
        \\            if test -z "$path"
        \\                set path $token
        \\            else
        \\                set path "$path $token"
        \\            end
        \\        end
        \\    end
        \\    echo $path
        \\end
        \\
        \\function __godot_cli_at
        \\    set -l current (__godot_cli_path)
        \\    test "$current" = "$argv[1]"
        \\end
        \\
        \\# No bare file completion; leaf commands opt back in with -F below.
        \\complete -c {s} -f
        \\
        \\
    , .{tool_name});

    try w.writeAll("# Subcommands\n");
    for (root.children) |child| {
        try w.print("complete -c {s} -n '__godot_cli_at \"\"' -a '{s}' -d '", .{ tool_name, child.name });
        try writeSingleQuoteEscaped(w, child.summary);
        try w.writeAll("'\n");
    }
    for (all) |entry| {
        if (entry.command.children.len == 0) continue;
        for (entry.command.children) |child| {
            try w.print("complete -c {s} -n '__godot_cli_at \"{s}\"' -a '{s}' -d '", .{ tool_name, entry.path, child.name });
            try writeSingleQuoteEscaped(w, child.summary);
            try w.writeAll("'\n");
        }
    }

    try w.writeAll("\n# Global options\n");
    for (spec.global_options) |opt| {
        try w.print("complete -c {s}", .{tool_name});
        if (opt.short) |short_char| try w.print(" -s {c}", .{short_char});
        try w.print(" -l {s}", .{opt.long});
        if (opt.kind != .flag) try w.writeAll(" -r");
        try w.writeAll(" -d '");
        try writeSingleQuoteEscaped(w, opt.description);
        try w.writeAll("'\n");
    }

    try w.writeAll("\n# Command options\n");
    for (all) |entry| {
        for (entry.command.options) |opt| {
            try w.print("complete -c {s} -n '__godot_cli_at \"{s}\"'", .{ tool_name, entry.path });
            if (opt.short) |short_char| try w.print(" -s {c}", .{short_char});
            try w.print(" -l {s}", .{opt.long});
            if (opt.kind != .flag) try w.writeAll(" -r");
            try w.writeAll(" -d '");
            try writeSingleQuoteEscaped(w, opt.description);
            try w.writeAll("'\n");
        }
    }

    try w.writeAll("\n# Commands that take file or directory arguments\n");
    for (all) |entry| {
        if (entry.command.handler == null) continue;
        try w.print("complete -c {s} -F -n '__godot_cli_at \"{s}\"'\n", .{ tool_name, entry.path });
    }
}

/// `name:description` pair for zsh `_describe`, single-quoted for the shell.
fn writeZshPair(
    w: *std.Io.Writer,
    prefix: []const u8,
    name: []const u8,
    description: []const u8,
) !void {
    try w.writeAll("'");
    try w.writeAll(prefix);
    try writeSingleQuoteEscaped(w, name);
    try w.writeAll(":");
    for (description) |byte| switch (byte) {
        ':' => try w.writeAll("\\:"),
        '\'' => try w.writeAll("'\\''"),
        '\n' => try w.writeAll(" "),
        else => try w.writeByte(byte),
    };
    try w.writeAll("'");
}

fn writeSingleQuoteEscaped(w: *std.Io.Writer, text: []const u8) !void {
    for (text) |byte| switch (byte) {
        '\'' => try w.writeAll("'\\''"),
        '\n' => try w.writeAll(" "),
        else => try w.writeByte(byte),
    };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// A small tree with the shapes that trip generators up: nesting, an option
/// with a value, and descriptions carrying a colon, a quote, and a pipe.
const test_root = spec.CommandSpec{
    .name = "godot-cli",
    .summary = "Test root",
    .children = &.{
        .{
            .name = "ping",
            .summary = "Framework health check",
            .handler = null,
        },
        .{
            .name = "scene",
            .summary = "Scene commands",
            .children = &.{
                .{
                    .name = "node",
                    .summary = "Node commands",
                    .children = &.{
                        .{
                            .name = "add",
                            .summary = "Add a child node",
                            .description = "Long form: adds one node.",
                            .options = &.{
                                .{ .long = "parent", .kind = .string, .description = "Parent path: viewport form" },
                                .{ .long = "dry-run", .description = "Report what would change; don't write" },
                                .{ .long = "mode", .kind = .string, .description = "One of a|b", .default_value = "a" },
                            },
                            .positionals = &.{
                                .{ .name = "file", .kind = .path, .description = "Scene file" },
                                .{ .name = "node", .required = false, .description = "Node path" },
                            },
                            .handler = @ptrFromInt(@alignOf(fn () void)),
                        },
                    },
                },
            },
        },
    },
};

test "markdown reference lists every command and option" {
    const allocator = std.testing.allocator;

    const text = try markdown(allocator, &test_root, "godot-cli", "Test summary");
    defer allocator.free(text);

    try std.testing.expect(std.mem.indexOf(u8, text, "### `godot-cli scene node add`") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "(#godot-cli-scene-node-add)") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "| `--parent` | `<value>` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "godot-cli scene node add [options] <file> [node]") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "| `[node]` | Node path (optional) |") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "| `a` |") != null);
    // A pipe inside a description would otherwise end the table cell.
    try std.testing.expect(std.mem.indexOf(u8, text, "One of a\\|b") != null);
}

test "man page escapes roff control characters and wraps source lines" {
    const allocator = std.testing.allocator;

    const text = try manPage(allocator, &test_root, "godot-cli", "Test summary", "1.2.3", "2026-01-02");
    defer allocator.free(text);

    try std.testing.expect(std.mem.startsWith(u8, text, ".TH GODOT\\-CLI 1 \"2026-01-02\""));
    try std.testing.expect(std.mem.indexOf(u8, text, ".SS godot\\-cli scene node add") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "\\fB\\-\\-dry\\-run\\fR") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "(default: a)") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, ".TP\n\\fIfile\\fR\nScene file\n") != null);

    var lines = std.mem.splitScalar(u8, text, '\n');
    while (lines.next()) |line| {
        try std.testing.expect(line.len <= 80);
    }
}

test "bash completions resolve nested command paths" {
    const allocator = std.testing.allocator;

    const text = try completions(allocator, &test_root, "godot-cli", .bash);
    defer allocator.free(text);

    try std.testing.expect(std.mem.indexOf(u8, text, "'scene node')\n            echo \"add\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "--parent --dry-run --mode") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "'scene node add') return 0 ;;") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "complete -F _godot_cli godot-cli") != null);
}

test "zsh completions escape colons in descriptions" {
    const allocator = std.testing.allocator;

    const text = try completions(allocator, &test_root, "godot-cli", .zsh);
    defer allocator.free(text);

    try std.testing.expect(std.mem.startsWith(u8, text, "#compdef godot-cli"));
    // An unescaped colon would split the _describe pair in the wrong place.
    try std.testing.expect(std.mem.indexOf(u8, text, "'--parent:Parent path\\: viewport form'") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "'add:Add a child node'") != null);
}

test "fish completions mark value options as requiring an argument" {
    const allocator = std.testing.allocator;

    const text = try completions(allocator, &test_root, "godot-cli", .fish);
    defer allocator.free(text);

    try std.testing.expect(std.mem.indexOf(u8, text, "-n '__godot_cli_at \"scene node\"' -a 'add'") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "-l parent -r -d") != null);
    try std.testing.expect(std.mem.indexOf(u8, text, "-l dry-run -d") != null);
    // Apostrophes in a description would otherwise close the quoted string.
    try std.testing.expect(std.mem.indexOf(u8, text, "don'\\''t write") != null);
}
