# bash completion for godot-cli — generated by `godot-cli completions bash`.
#
# Install: source this file from ~/.bashrc, or copy it into
# /usr/local/etc/bash_completion.d/ (Homebrew) or /etc/bash_completion.d/.

_godot_cli_children() {
    case "$1" in
        '')
            echo "help ping uid scene resource catalog batch project completions man reference"
            ;;
        'uid')
            echo "encode decode create-for-path scene-id cache session"
            ;;
        'uid scene-id')
            echo "generate"
            ;;
        'uid cache')
            echo "list lookup"
            ;;
        'uid session')
            echo "import"
            ;;
        'scene')
            echo "new refs ext sub inspect node connection instance template plan apply diff restore validate validate-batch set-property normalize retarget-ext round-trip compare-godot"
            ;;
        'scene ext')
            echo "add remove"
            ;;
        'scene sub')
            echo "add remove"
            ;;
        'scene node')
            echo "list get add remove rename reparent"
            ;;
        'scene connection')
            echo "list add remove"
            ;;
        'scene instance')
            echo "add"
            ;;
        'scene template')
            echo "list show copy"
            ;;
        'resource')
            echo "inspect validate validate-batch set-property normalize retarget-ext round-trip compare-godot"
            ;;
        'catalog')
            echo "add relink scan list show validate search export"
            ;;
        'project')
            echo "show apply input settings autoload plugins rendering physics"
            ;;
        'project input')
            echo "list apply validate"
            ;;
        'project settings')
            echo "list get set apply validate"
            ;;
        'project autoload')
            echo "list apply validate"
            ;;
        'project plugins')
            echo "list enable disable apply validate"
            ;;
        'project rendering')
            echo "list apply validate"
            ;;
        'project physics')
            echo "list apply validate"
            ;;
        *)
            echo ""
            ;;
    esac
}

_godot_cli_options() {
    case "$1" in
        'uid create-for-path')
            echo "--project-name --resource-path"
            ;;
        'uid scene-id generate')
            echo "--seed --count"
            ;;
        'uid cache list')
            echo "--project-root"
            ;;
        'uid cache lookup')
            echo "--project-root"
            ;;
        'uid session import')
            echo "--referrer --from --id-session --project-root"
            ;;
        'scene new')
            echo "--output --root-name --root-type --project-root --resource-path --no-prepare-save --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene refs')
            echo "--project-root"
            ;;
        'scene ext add')
            echo "--type --path --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene ext remove')
            echo "--project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene sub add')
            echo "--type --property --value --raw-value --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene sub remove')
            echo "--project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene inspect')
            echo "--project-root --no-validate --parse-properties --no-parse-properties"
            ;;
        'scene node list')
            echo "--project-root"
            ;;
        'scene node get')
            echo "--node-name --parent --project-root"
            ;;
        'scene node add')
            echo "--parent --name --type --property --value --raw-value --unique-name --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene node remove')
            echo "--recursive --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene node rename')
            echo "--parent --name --type --property --value --raw-value --unique-name --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene node reparent')
            echo "--parent --name --type --property --value --raw-value --unique-name --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene connection add')
            echo "--from --signal --to --method --deferred --one-shot --binds --unbinds --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene connection remove')
            echo "--from --signal --to --method --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene instance add')
            echo "--parent --name --scene --catalog-id --editable --unique-name --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene template list')
            echo "--templates-root --content --no-parse-properties"
            ;;
        'scene template show')
            echo "--templates-root --content --no-parse-properties"
            ;;
        'scene template copy')
            echo "--templates-root --rename-node --set-property --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene plan')
            echo "--intent --patch --write-patch --project-root"
            ;;
        'scene apply')
            echo "--patch --intent --snapshot --auto-snapshot --record-undo --write-undo-patch --no-strict --preview-properties --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene diff')
            echo "--properties --project-root"
            ;;
        'scene restore')
            echo "--from --snapshot --dry-run"
            ;;
        'scene validate')
            echo "--project-root"
            ;;
        'scene validate-batch')
            echo "--project-root"
            ;;
        'scene set-property')
            echo "--property --value --raw-value --node --node-name --section-line --section --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene normalize')
            echo "--project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene retarget-ext')
            echo "--from --to --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'scene round-trip')
            echo "--output --dry-run"
            ;;
        'scene compare-godot')
            echo "--reference"
            ;;
        'resource inspect')
            echo "--project-root --no-validate --parse-properties --no-parse-properties"
            ;;
        'resource validate')
            echo "--project-root"
            ;;
        'resource validate-batch')
            echo "--project-root"
            ;;
        'resource set-property')
            echo "--property --value --raw-value --section-line --section --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'resource normalize')
            echo "--project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'resource retarget-ext')
            echo "--from --to --project-root --resource-path --no-prepare-save --output --dry-run --id-session --no-id-session --godot-save-format --normalize-properties"
            ;;
        'resource round-trip')
            echo "--output --dry-run"
            ;;
        'resource compare-godot')
            echo "--reference"
            ;;
        'catalog add')
            echo "--project-root --id --summary --when-to-use --when-not-to-use --notes --tags --related-ids --update --output --dry-run"
            ;;
        'catalog relink')
            echo "--project-root --dry-run"
            ;;
        'catalog scan')
            echo "--project-root"
            ;;
        'catalog list')
            echo "--project-root"
            ;;
        'catalog show')
            echo "--project-root"
            ;;
        'catalog validate')
            echo "--project-root"
            ;;
        'catalog search')
            echo "--project-root --tags --query"
            ;;
        'catalog export')
            echo "--project-root --output --dry-run"
            ;;
        'batch')
            echo "--file --json-body"
            ;;
        'project')
            echo "--project-root"
            ;;
        'project show')
            echo "--project-root"
            ;;
        'project apply')
            echo "--project-root --intent --file --dry-run"
            ;;
        'project input list')
            echo "--project-root"
            ;;
        'project input apply')
            echo "--project-root --intent --file --dry-run"
            ;;
        'project input validate')
            echo "--project-root"
            ;;
        'project settings list')
            echo "--project-root --section"
            ;;
        'project settings get')
            echo "--project-root --section --key"
            ;;
        'project settings set')
            echo "--project-root --section --key --value --raw --dry-run"
            ;;
        'project settings apply')
            echo "--project-root --intent --file --dry-run"
            ;;
        'project settings validate')
            echo "--project-root --section"
            ;;
        'project autoload list')
            echo "--project-root"
            ;;
        'project autoload apply')
            echo "--project-root --intent --file --dry-run"
            ;;
        'project autoload validate')
            echo "--project-root"
            ;;
        'project plugins list')
            echo "--project-root"
            ;;
        'project plugins enable')
            echo "--project-root --plugin --path --dry-run"
            ;;
        'project plugins disable')
            echo "--project-root --plugin --path --dry-run"
            ;;
        'project plugins apply')
            echo "--project-root --intent --file --dry-run"
            ;;
        'project plugins validate')
            echo "--project-root"
            ;;
        'project rendering list')
            echo "--project-root"
            ;;
        'project rendering apply')
            echo "--project-root --intent --file --dry-run"
            ;;
        'project rendering validate')
            echo "--project-root"
            ;;
        'project physics list')
            echo "--project-root"
            ;;
        'project physics apply')
            echo "--project-root --intent --file --dry-run"
            ;;
        'project physics validate')
            echo "--project-root"
            ;;
        'completions')
            echo "--output"
            ;;
        'man')
            echo "--output"
            ;;
        'reference')
            echo "--output --format"
            ;;
        *)
            echo ""
            ;;
    esac
}

_godot_cli_takes_args() {
    case "$1" in
        'ping') return 0 ;;
        'uid encode') return 0 ;;
        'uid decode') return 0 ;;
        'uid create-for-path') return 0 ;;
        'uid scene-id generate') return 0 ;;
        'uid cache list') return 0 ;;
        'uid cache lookup') return 0 ;;
        'uid session import') return 0 ;;
        'scene new') return 0 ;;
        'scene refs') return 0 ;;
        'scene ext add') return 0 ;;
        'scene ext remove') return 0 ;;
        'scene sub add') return 0 ;;
        'scene sub remove') return 0 ;;
        'scene inspect') return 0 ;;
        'scene node list') return 0 ;;
        'scene node get') return 0 ;;
        'scene node add') return 0 ;;
        'scene node remove') return 0 ;;
        'scene node rename') return 0 ;;
        'scene node reparent') return 0 ;;
        'scene connection list') return 0 ;;
        'scene connection add') return 0 ;;
        'scene connection remove') return 0 ;;
        'scene instance add') return 0 ;;
        'scene template list') return 0 ;;
        'scene template show') return 0 ;;
        'scene template copy') return 0 ;;
        'scene plan') return 0 ;;
        'scene apply') return 0 ;;
        'scene diff') return 0 ;;
        'scene restore') return 0 ;;
        'scene validate') return 0 ;;
        'scene validate-batch') return 0 ;;
        'scene set-property') return 0 ;;
        'scene normalize') return 0 ;;
        'scene retarget-ext') return 0 ;;
        'scene round-trip') return 0 ;;
        'scene compare-godot') return 0 ;;
        'resource inspect') return 0 ;;
        'resource validate') return 0 ;;
        'resource validate-batch') return 0 ;;
        'resource set-property') return 0 ;;
        'resource normalize') return 0 ;;
        'resource retarget-ext') return 0 ;;
        'resource round-trip') return 0 ;;
        'resource compare-godot') return 0 ;;
        'catalog add') return 0 ;;
        'catalog relink') return 0 ;;
        'catalog scan') return 0 ;;
        'catalog list') return 0 ;;
        'catalog show') return 0 ;;
        'catalog validate') return 0 ;;
        'catalog search') return 0 ;;
        'catalog export') return 0 ;;
        'batch') return 0 ;;
        'project show') return 0 ;;
        'project apply') return 0 ;;
        'project input list') return 0 ;;
        'project input apply') return 0 ;;
        'project input validate') return 0 ;;
        'project settings list') return 0 ;;
        'project settings get') return 0 ;;
        'project settings set') return 0 ;;
        'project settings apply') return 0 ;;
        'project settings validate') return 0 ;;
        'project autoload list') return 0 ;;
        'project autoload apply') return 0 ;;
        'project autoload validate') return 0 ;;
        'project plugins list') return 0 ;;
        'project plugins enable') return 0 ;;
        'project plugins disable') return 0 ;;
        'project plugins apply') return 0 ;;
        'project plugins validate') return 0 ;;
        'project rendering list') return 0 ;;
        'project rendering apply') return 0 ;;
        'project rendering validate') return 0 ;;
        'project physics list') return 0 ;;
        'project physics apply') return 0 ;;
        'project physics validate') return 0 ;;
        'completions') return 0 ;;
        'man') return 0 ;;
        'reference') return 0 ;;
        *) return 1 ;;
    esac
}

_godot_cli_global_options="--help --version --json --verbose --request --request-file --request-stdin"

_godot_cli() {
    local cur path="" word children candidates
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"

    local index
    for (( index = 1; index < COMP_CWORD; index++ )); do
        word="${COMP_WORDS[index]}"
        case "$word" in
            -*) continue ;;
        esac
        children=" $(_godot_cli_children "$path") "
        if [[ "$children" == *" $word "* ]]; then
            path="${path:+$path }$word"
        fi
    done

    candidates="$(_godot_cli_children "$path") $(_godot_cli_options "$path") $_godot_cli_global_options"
    COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )

    # Leaf commands nearly all take a path; offer files once the word
    # being completed is clearly not a flag.
    if [[ "$cur" != -* ]] && _godot_cli_takes_args "$path"; then
        COMPREPLY+=( $(compgen -f -- "$cur") )
    fi
}

complete -F _godot_cli godot-cli
